{"name": "Проверка невозможности создания курьера c существующим логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x00000250FA73DFD0>, get_url = 'https://qa-scooter.praktikum-services.ru/api/v1/courier'\nget_exist_data = {'firstName': 'tbzxwtsnfw', 'login': 'djgckqwoup', 'password': 'newnpadolywqu'}\n\n    @allure.title('Проверка невозможности создания курьера c существующим логином')\n    def test_create_courier_with_exist_login_unavailable_success(self, get_url, get_exist_data):\n        with allure.step('Формирование тела запроса'):\n            payload = get_exist_data\n            old_password = get_exist_data['password']\n            payload['password'] = f\"new{get_exist_data['password']}\"\n        with allure.step('Получение ответа'):\n            response = requests.post(url=get_url, data=payload)\n        with allure.step('Проверка тела ответа'):\n>           assert response.json()['message'] == Constants.ERROR_MESSAGE_FOR_EXIST_LOGIN\nE           AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE             - Этот логин уже используется\nE             + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:71: AssertionError"}, "steps": [{"name": "Формирование тела запроса", "status": "passed", "start": 1706722152987, "stop": 1706722152987}, {"name": "Получение ответа", "status": "passed", "start": 1706722152987, "stop": 1706722153259}, {"name": "Проверка тела ответа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.\n", "trace": "  File \"D:\\Dev\\qa_python_sprint_7\\tests\\test_create_courier.py\", line 71, in test_create_courier_with_exist_login_unavailable_success\n    assert response.json()['message'] == Constants.ERROR_MESSAGE_FOR_EXIST_LOGIN\n    \n"}, "start": 1706722153259, "stop": 1706722153260}], "attachments": [{"name": "stdout", "source": "3022ca0f-2eca-4649-a5d7-0b234cc3c86d-attachment.txt", "type": "text/plain"}], "start": 1706722152986, "stop": 1706722153264, "uuid": "718b52d3-69e7-4771-bcd1-ea72ebcc9cc0", "historyId": "788a8f740c578dd029f3f2748cfba7b4", "testCaseId": "788a8f740c578dd029f3f2748cfba7b4", "fullName": "tests.test_create_courier#test_create_courier_with_exist_login_unavailable_success", "labels": [{"name": "tag", "value": "get_url('create_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-0EOUJEC"}, {"name": "thread", "value": "5888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}